loki:
  enabled: true
  service:
    type: NodePort
    nodePort: 31000
    port: 3100

promtail:
  enabled: false

fluent-bit:
  enabled: false

grafana:
  enabled: true
  service:
    type: NodePort
    nodePort: 31300
