# Default values for fluent-bit.

# kind -- DaemonSet or Deployment
kind: DaemonSet

## https://docs.fluentbit.io/manual/administration/configuring-fluent-bit
config:
  ## https://docs.fluentbit.io/manual/service
  service: |
    @INCLUDE fluentbit-common-outputs.conf

    [SERVICE]
      Flush 5
      Daemon Off
      Log_Level warning
      Parsers_File custom_parsers.conf
      HTTP_Server On
      HTTP_Listen 0.0.0.0
      HTTP_Port 2020
      storage.path /var/log/flb-storage/
      storage.sync normal
      storage.checksum off
      storage.backlog.mem_limit 5M
      storage.metrics on

  ## https://docs.fluentbit.io/manual/pipeline/inputs
  inputs: |
    [INPUT]
      Name              tail
      Alias             kube_container_logs
      Tag               kube.<namespace_name>.<container_name>.<pod_name>.<docker_id>-
      Tag_Regex         (?<pod_name>[a-z0-9](?:[-a-z0-9]*[a-z0-9])?(?:\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)_(?<namespace_name>[^_]+)_(?<container_name>.+)-(?<docker_id>[a-z0-9]{64})\.log$
      Buffer_Chunk_Size 512k
      Buffer_Max_Size   5m
      Path              /var/log/containers/*.log
      Parser            docker
      DB                /var/log/flb_kube.db
      Mem_Buf_Limit     512MB
      Skip_Long_Lines   On
      Refresh_Interval  10
    [INPUT]
      Name              tail
      Alias             kube_audit
      Tag               kube_audit
      Buffer_Chunk_Size 512k
      Buffer_Max_Size   5m
      Path              /var/log/kubernetes/audit/audit.log
      Parser            json
      DB                /var/log/flb_kube_audit.db
      Mem_Buf_Limit     128MB
      Skip_Long_Lines   On
      Refresh_Interval  10

  ## https://docs.fluentbit.io/manual/pipeline/filters
  filters: |
    [FILTER]
      Name  modify
      Alias add_cluster_name
      Match *
      Add   x_cluster ${K8S_CLUSTER}
    [FILTER]
      Name        modify
      Alias       kube_audit_minikube
      Match_Regex ^(kube_audit)$
      Add         x_cluster ${K8S_CLUSTER}

  ## https://docs.fluentbit.io/manual/pipeline/outputs
  outputs: ""

  ## https://docs.fluentbit.io/manual/pipeline/parsers
  ## https://github.com/fluent/fluent-bit/blob/master/conf/parsers.conf
  customParsers: |
    [PARSER]
      Name        json
      Format      json
      Time_Key    time
      Time_Format %d/%b/%Y:%H:%M:%S %z
    [PARSER]
      Name         docker
      Format       json
      Time_Key     time
      Time_Format  %Y-%m-%dT%H:%M:%S.%L
      Time_Keep    On
